@startuml "handling_publisher"

interface "Publisher" as pub
struct "HandlingPublisher" as pubHandler{
    {field} delegate: Publisher
}
interface "Handler" as hndl

pubHandler .u.|> pub
pubHandler .u.|> hndl

@enduml