[package]
name = "ropes_primitives"
version = "0.1.0"
edition = "2021"

[lib]
doctest = true

[dependencies]
enclose = "1.1.8"
delegate = "0.9.0"

[dev-dependencies]
ropes_lib = { path = "../ropes_lib" }