[package]
name = "rope-lib"
version = "0.1.0"
edition = "2021"

[lib]
doctest = true

[dependencies]
enclose = "1.1.8"
delegate = "0.9.0"

[[example]]
name = "counting-hello-world"

[[example]]
name = "prefix-logger"

