[package]
name = "roopes-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
doctest = true

[dependencies]
enclose = "1.1.8"

[[example]]
name = "roopes-demo-bin"
