@startuml "abstract_factory"

interface "AbstractFactory" as fact<Result> {
    {method} + create(): Result
}

struct "LambdaAbstractFactory" as lbdfact<Result> {
    {field} - delegate: Fn() -> Result
    {method} + new(delegate: Fn() -> Result)
}

lbdfact .u.|> fact

@enduml