[package]
name = "ropes_patterns"
version = "0.1.0"
edition = "2021"

[lib]
doctest = true

[dependencies]
enclose = "1.1.8"
delegate = "0.9.0"
ropes_primitives = { path = "../ropes_primitives" }


[dev-dependencies]
ropes ={ path = "../ropes_lib"}